;; 基础配置

;;; 关闭无用快捷键
(global-unset-key (kbd "C-x C-z"))

;;; 前后增加括号、符号等
;; electric-pair-mode
(electric-pair-mode t)

;;; Tab
;; 设置 Tab 的长度为 4
(setq default-tab-width 4)

;; 使用y-n代替yes-no
(defalias 'yes-or-no-p 'y-or-n-p)

;; 配置制表符
(setq default-tab-width 4)

;; 启用 winner-mode
(winner-mode 1)

;; 配置自动备份位置
(setq backup-directory-alist (quote (("." . "~/.backup-file"))))

;; 高亮成对括号
(show-paren-mode 1)

;; 修复区域选择与输入法的冲突
(global-unset-key (kbd "C-SPC"))
(global-set-key (kbd "C-x C-2") 'set-mark-command)

;; 取消 C-z 最小化窗口
(global-unset-key (kbd "C-z"))

;; 关闭工具栏
(tool-bar-mode 0)
;; 关闭菜单栏
(menu-bar-mode 0)
;; 关闭滚动条
(scroll-bar-mode 0)
;; 关闭启动页面
(setq inhibit-startup-screen t)

;; 显示行号
(global-linum-mode t)

;; 显示光标位置
(column-number-mode t)

;; 字符集设置
(prefer-coding-system 'utf-8)

(setenv "LANG" "en_US.UTF-8")
(setenv "LC_ALL" "en_US.UTF-8")
(setenv "LC_CTYPE" "en_US.UTF-8")

;; 时间设置
;; 设定时间日期的格式
(setq display-time-format "%Y-%m-%d %H:%M")
;; 启用时间显示设置
(display-time-mode 1)

;;; 高亮
;; 当前行高亮
(global-hl-line-mode 1)
;; 行尾空格高亮
(global-whitespace-mode)
(setq whitespace-style '(face trailing empty tab-mark))

;;; Socks 代理
;;(setq url-gateway-method 'socks)
;;(setq socks-server '("V2ray" "127.0.0.1" 1289 5))

;;; 字体配置
;; 由 cnfonts 生成
;; Auto generated by cnfonts
;; <https://github.com/tumashu/cnfonts>
(set-face-attribute
 'default nil
 :font (font-spec :name "-outline-DejaVu Sans Mono-bold-italic-normal-mono-*-*-*-*-c-*-iso10646-1"
                  :weight 'normal
                  :slant 'normal
                  :size 10.0))
(dolist (charset '(kana han symbol cjk-misc bopomofo))
  (set-fontset-font
   (frame-parameter nil 'font)
   charset
   (font-spec :name "-outline-微软雅黑-normal-normal-normal-sans-*-*-*-*-p-*-iso10646-1"
              :weight 'normal
              :slant 'normal
              :size 12.0)))

;;; 矩形编辑
(cua-selection-mode t)

;;; eshell 配置
;; 常用命令
(defalias 'ff 'find-file)
;; 基础配置
(setq
 eshell-save-history-on-exit   t
      eshell-history-size           512
      eshell-hist-ignoredups        t
      eshell-cmpl-ignore-case       t
      eshell-cp-interactive-query   t
      eshell-ln-interactive-query   t
      eshell-mv-interactive-query   t
      eshell-rm-interactive-query   t
      eshell-mv-overwrite-files     nil
      eshell-highlight-prompt   t
      ;; 提示符设置，下面两项必须对应起来，
      ;; 否则会报 read-only，并且不能补全什么的
      eshell-prompt-regexp      "^[^#$\n]* [#>]+ "
      eshell-prompt-function    (lambda nil
                                  (concat
                                   (abbreviate-file-name
                                    (eshell/pwd))
                                   (if
                                       (=
                                        (user-uid)
                                        0)
                                       " # " " >>> ")))
)

(provide 'init-startup)
